/*
 * COVID-19 Statistics API
 * API for COVID-19 statistics including regions and provinces.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mmakomsrv.api;

import com.mmakomsrv.model.InlineResponse200;
import com.mmakomsrv.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Get provinces
     *
     * Retrieve a list of provinces for a given region.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void provincesGetTest() throws Exception {
        String iso = null;
        Integer page = null;
        Integer size = null;
        InlineResponse2001 response = api.provincesGet(iso, page, size);

        // TODO: test validations
    }
    
    /**
     * Get regions
     *
     * Retrieve a list of regions.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void regionsGetTest() throws Exception {
        Integer page = null;
        Integer size = null;
        InlineResponse200 response = api.regionsGet(page, size);

        // TODO: test validations
    }
    
}
